sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
install: 
  - pip install -r requirements.txt
  - pip install pylint
  - pip install -r test_requirements.txt
script:
  - pylint otcbtc_client
  - tox
after_success:
  - codecov
